<template>
  <div>
    <section style="height: 100%">
      <div class="container" style="background-color: white;">
        <br />
        <div class="content has-text-centered">
          <h1 class="title is-4">
            Effects and Treatment
          </h1>
        <div class="table-container">
        <table class="table is-scrollable is-stripped is-bordered is-hoverable">
<thead><tr><th title="Field #1">Constituent</th>
<th title="Field #2">Risk</th>
<th title="Field #3">Effect</th>
<th title="Field #4">Treatment</th>
</tr></thead>
<tbody><tr>
<td>Aluminium </td>
<td>operational</td>
<td>The main effects of aluminium in domestic water are aesthetic, relating to discolouration in the presence of iron or manganese. Aluminium is also used in water treatment processes, which may result in increased concentrations of aluminium in the final water. Prolonged exposure to aluminium has been implicated in chronic neurological disorders such as dialysis dementia and Alzheimer&#39;s disease. It is, however, not clear whether the presence of aluminium causes such conditions or is an indicator of other factors. Therefore, the link between aluminium in water and adverse effects on human health remains to be conclusively identified. Although not strictly related to consumption of drinking water, the consumption of large quantities of aluminium hydroxide in the form of proprietary &quot;antacids&quot; for the relief of minor stomach discomforts can lead to excessive loss of phosphate.</td>
<td>The formation and precipitation of insoluble aluminium salts. Aluminium ions will react with alkalinity in the water to form aluminium hydroxide which is insoluble in the pH range 6.7 - 7.6. The particles formed may be very light and difficult to settle without the addition of a polyelectrolyte to flocculate and increase the specific gravity of the particles. However, if the water has a high concentration of suspended clay particles, settlement is fairly fast and the addition of polyelectrolytes is unnecessary. Light particles can also be settled out in properly designed sedimentation tanks without polyelectrolytes. An alternative is to dose with a phosphate solution and remove the aluminium as insoluble aluminium phosphate. ! Exchange of sodium by aluminium in a cation exchange column along with calcium and magnesium. ! Removal of aluminium together with other dissolved components using desalination techniques such as demineralisation by ion exchange, membrane processes or distillation methods. All of the methods described require skilled monitoring and control, and generate a concentrated waste stream that may cause disposal difficulties.</td>
</tr>
<tr>
<td>Ammonia as N </td>
<td>aesthetic</td>
<td>The chemistry of ammonia is very complex, especially where transition metals are presentin water, and while ammonia itself is of relatively low toxicity, this is not necessarily thecase for some of its organometallic complexes. Taste and odour complaints are likely to occur if the ammonia concentration exceeds 1.5 mg/R. High concentrations of ammonia can also give rise to nitrite, which is potentiallytoxic, especially to infants.</td>
<td>At near-neutral pH, the non-toxic ammonium ion predominates while the toxic-free Options ammonia form predominates as the pH increases to approximately 11. The volatile nature of the free ammonia form provides a useful treatment technique to remove ammonia from water supplies. The pH of the water can be increased to greater than 11.0 by the addition of a strong alkali such as sodium hydroxide, to convert all the ammonia to the volatile free form. Treatment involves spraying water in droplet form down through a vertical stripping tower, through which air is blown counter current to the water flow. This strips the volatile ammonia from solution into the atmosphere with the air stream, leaving ammonia residuals of less than 1.0 mg/R. Air stripping of ammonia may, however, cause a local smell nuisance if the ammonia concentrations are significantly high. The water is then made usable by re-adjusting the pH to approximately 7. Any residual ammonia is likely to exist as the non-toxic ammonium ion. If total removal of ammonia is required the water can be passed through commercially available ion exchange resins which have an affinity for ammonia. Ammonia removal systems are not suited to treating domestic water on a household scale.</td>
</tr>
<tr>
<td>Antimony </td>
<td>health</td>
<td>There is some evidence for the carcinogenicity of certain antimony compounds by inhalation, however, there are no data to indicate carcinogenicity by the oral route.Tolerable daily intake (TDI) 6 ?g/kg body weight, based on a NOAEL of 6.0 mg/kg body weight per day for decreased body weight gain and reduced food and water intake in a 90-day study in which rats were administered potassium antimony tartrate in drinking-water, using an uncertainty factor of 1000 (100 for interspecies and intraspecies variation, 10 for the short duration of the study)</td>
<td> </td>
</tr>
<tr>
<td>Arsenic </td>
<td>health</td>
<td>Carcinogenic ? skin, lung and bladder.  The International Agency for Research on Cancer (IARC) has classified arsenic and arsenic compounds as carcinogenic to humans.Toxic effects = Neurological effects, memory, and intellectual function. Arsenic accumulates in the body during childhood and may induce neurobehavioral abnormalities during puberty, and neuro-behavioural changes as an adult. Foetal mortality and preterm birth increased as exposure to arsenic increased. It has also been associated with cardiovascular disease and diabetes.</td>
<td>Arsenic is most effectively removed from water in its pentavalent form. Trivalent arsenic is first converted to the pentavalent form using an appropriate oxidising agent such as chlorine or potassium permanganate. Pentavalent arsenic is effectively removed from water using conventional coagulation and flocculation processes followed by settlement and filtration. Suitable coagulants include aluminium sulphate, ferric salts and lime. The process requires monitoring to ensure the arsenic is effectively removed. The process will also generate a watery sludge rich in arsenic, that may present disposal problems.</td>
</tr>
<tr>
<td>Barium </td>
<td>health</td>
<td>TBD</td>
<td>TBD</td>
</tr>
<tr>
<td>Boron </td>
<td>health</td>
<td>Respiratory, cardiovascular, gastrointestinal, haematological, musculoskeletal, and renal effects in animals and respiratory effects and dermal/ocular effects in humansTDI 0.17 mg/kg body weight, based on a BMDL05 of 10.3 mg/kg body weight per day for developmental toxicity (decreased foetal body weight in rats) and an uncertainty factor of 60 (10 for interspecies variation and 6 for intra-species variation)</td>
<td>TBD</td>
</tr>
<tr>
<td>Bromodichloromethane </td>
<td>health</td>
<td>The similarity in effects and risks of the four main THM compounds allow them to beevaluated as a group and in practice only the total THM value is of significance and not theindividual THM concentrations. The criteria indicate an average risk of contracting cancerof one in 10 , over and above the background risk at a total THM concentration of 1005&#181;g/R. This is greater than the &quot;application safety factor&quot; used in estimating human risk,which is in the order of 10 . Further, the apparently greater risk with3bromodichloromethane than with chloroform is vastly overshadowed by the uncertainty ofanimal to human extrapolations used in these calculations. Sufficient animal experimentsas well as confirmative epidemiological studies have shown that there is a very small butsignificant risk of increased cancer incidence of the bowel and bladder from drinkingchlorinated water as opposed to unchlorinated ground water. The risk levels are, however,at the borderline of detection and some well-designed studies do not show a difference inrisk.The most commonly occurring THM is chloroform. In pure form this has stronganaesthetic properties and was one of the first substances used as an anaesthetic. Longterm exposure to dose levels of chloroform in excess of 15 mg/kg can induce pathologicalchanges in the liver, kidney and thyroid gland. When fed to experimental animals in highdosages over a long period, tumour induction has been observed. Epidemiological studieson human populations have been equivocal at exposure levels normally encountered.Extrapolation from animal studies suggests that the risk level for man at a lifetime exposureto 200 &#181;g/R in drinking water is a cancer risk of one in 10 , over and above the background 5cancer risk.For bromoform, there is evidence of toxicity at high levels of exposure and equivocalevidence of tumour induction, as in the case of chloroform, with a risk level of one in 105to a concentration of 100 &#181;g/R for lifetime exposure. In the case of bromodichloromethane, toxicity with liver and kidney damage is observed inexperimental animals at high levels with long-term exposure. The cancer risk level for a onein 10 incidence over a lifetime, is extrapolated from animal experiments to give a5concentration of 60 &#181;g/R in drinking water.Dibromochloromethane has similar toxic and carcinogenic risks to bromoform with a risklevel of one in 10 for a lifetime risk of cancer, at a concentration of 100 &#181;g/R in drinking 5water</td>
<td>Most forms of THMs are volatile. Treatment methods make use of this and subject the  water to air stripping in a vertical tower using a countercurrent stream of air blown upthrough the tower to strip the volatile substances into the atmosphere.However, some THMs are not easily volatilised and treatment of the raw water to removethe THM precursors (such as humic substances), may be required. Methods for removalinclude:! Slow sand filtration to remove trace organics from the water.! Coagulation, flocculation, clarification and filtration to remove particulate matterincluding organic colloids.! Adsorption of the organics onto activated carbon.! Oxidation of the organics using a powerful oxidising agent such as hydrogen, peroxide,ozone or peroxone. Chlorine is not a suitable oxidant as it will form THMs.A number of these methods may need to be applied in succession to achieve the requiredwater quality. High levels of treatment skills are needed to achieve satisfactory results,together with sophisticated analytical facilities.</td>
</tr>
<tr>
<td>Bromoform </td>
<td>health</td>
<td>The similarity in effects and risks of the four main THM compounds allow them to beevaluated as a group and in practice only the total THM value is of significance and not theindividual THM concentrations. The criteria indicate an average risk of contracting cancerof one in 10 , over and above the background risk at a total THM concentration of 1005&#181;g/R. This is greater than the &quot;application safety factor&quot; used in estimating human risk,which is in the order of 10 . Further, the apparently greater risk with3bromodichloromethane than with chloroform is vastly overshadowed by the uncertainty ofanimal to human extrapolations used in these calculations. Sufficient animal experimentsas well as confirmative epidemiological studies have shown that there is a very small butsignificant risk of increased cancer incidence of the bowel and bladder from drinkingchlorinated water as opposed to unchlorinated ground water. The risk levels are, however,at the borderline of detection and some well-designed studies do not show a difference inrisk.The most commonly occurring THM is chloroform. In pure form this has stronganaesthetic properties and was one of the first substances used as an anaesthetic. Longterm exposure to dose levels of chloroform in excess of 15 mg/kg can induce pathologicalchanges in the liver, kidney and thyroid gland. When fed to experimental animals in highdosages over a long period, tumour induction has been observed. Epidemiological studieson human populations have been equivocal at exposure levels normally encountered.Extrapolation from animal studies suggests that the risk level for man at a lifetime exposureto 200 &#181;g/R in drinking water is a cancer risk of one in 10 , over and above the background 5cancer risk.For bromoform, there is evidence of toxicity at high levels of exposure and equivocalevidence of tumour induction, as in the case of chloroform, with a risk level of one in 105to a concentration of 100 &#181;g/R for lifetime exposure. In the case of bromodichloromethane, toxicity with liver and kidney damage is observed inexperimental animals at high levels with long-term exposure. The cancer risk level for a onein 10 incidence over a lifetime, is extrapolated from animal experiments to give a5concentration of 60 &#181;g/R in drinking water.Dibromochloromethane has similar toxic and carcinogenic risks to bromoform with a risklevel of one in 10 for a lifetime risk of cancer, at a concentration of 100 &#181;g/R in drinking 5water</td>
<td>Most forms of THMs are volatile. Treatment methods make use of this and subject the  water to air stripping in a vertical tower using a countercurrent stream of air blown upthrough the tower to strip the volatile substances into the atmosphere.However, some THMs are not easily volatilised and treatment of the raw water to removethe THM precursors (such as humic substances), may be required. Methods for removalinclude:! Slow sand filtration to remove trace organics from the water.! Coagulation, flocculation, clarification and filtration to remove particulate matterincluding organic colloids.! Adsorption of the organics onto activated carbon.! Oxidation of the organics using a powerful oxidising agent such as hydrogen, peroxide,ozone or peroxone. Chlorine is not a suitable oxidant as it will form THMs.A number of these methods may need to be applied in succession to achieve the requiredwater quality. High levels of treatment skills are needed to achieve satisfactory results,together with sophisticated analytical facilities.</td>
</tr>
<tr>
<td>Cadmium </td>
<td>health</td>
<td>IARC has classified cadmium and cadmium compounds in Group 2A (probably carcinogenic to humans). However, there is no evidence of carcinogenicity by the oral route and no clear evidence for the genotoxicity of cadmium. The kidney is the main target organ for cadmium toxicityPTMI of 25 ?g/kg body weight is calculated, based on the relationship between ?2-microglobulin excretion in urine and cadmium excretion in urine for individuals who are 50 years of age and older.</td>
<td>Cadmium in water supplies is most conveniently removed by raising the pH andprecipitating the insoluble cadmium salts after the addition of lime or iron salts in the pHrange of 8.5 - 11.5. Precipitation is followed by settlement and filtration as in conventionalwater treatment. The precipitation process requires careful monitoring to ensure thatremoval is complete. To achieve very low residuals, it may be necessary to pass the streamthrough an ion exchange column charged with the appropriate resin.A watery cadmium-rich sludge or concentrate stream is generated in the processes, that maypresent disposal difficulties</td>
</tr>
<tr>
<td>Chloride as Cl- </td>
<td>aesthetic</td>
<td>Chloride is only detectable by taste at concentrations exceeding approximately 200 mg/R.A salty taste becomes quite distinctive at 400 mg/R and objectionable at greater than600 mg/R. At chloride concentrations greater than 2 000 mg/R nausea may occur, while at10 000 mg/R vomiting and dehydration may be induced.Chloride accelerates the corrosion rate of iron and certain other metals well below theconcentration at which it is detectable by taste. The threshold for an increased corrosionrate is approximately 50 mg/R. At chloride concentrations greater than 200 mg/R, there islikely to be a significant shortening of the lifetime of domestic appliances as a result ofcorrosion.</td>
<td>Chlorides are highly soluble and cannot be precipitated at concentrations usually present inwater. Chloride can be removed from water by electrolysis to form chlorine gas, liberatedat the anode. Electrolysis is not effective where the conductivity and the chlorideconcentration are low.More commonly, chloride is removed together with other ions using:! anion exchange resin beds, in which all significant anions will be removed; and! desalination techniques such as reverse osmosis and electrodialysis.The concentrated waste streams generated from ion exchange and desalination processesmay cause disposal difficulties. Desalination techniques require skilled operation, controland maintenance; capital and operating costs are typically high.</td>
</tr>
<tr>
<td>Chloroform </td>
<td>health</td>
<td>The similarity in effects and risks of the four main THM compounds allow them to beevaluated as a group and in practice only the total THM value is of significance and not theindividual THM concentrations. The criteria indicate an average risk of contracting cancerof one in 10 , over and above the background risk at a total THM concentration of 1005&#181;g/R. This is greater than the &quot;application safety factor&quot; used in estimating human risk,which is in the order of 10 . Further, the apparently greater risk with3bromodichloromethane than with chloroform is vastly overshadowed by the uncertainty ofanimal to human extrapolations used in these calculations. Sufficient animal experimentsas well as confirmative epidemiological studies have shown that there is a very small butsignificant risk of increased cancer incidence of the bowel and bladder from drinkingchlorinated water as opposed to unchlorinated ground water. The risk levels are, however,at the borderline of detection and some well-designed studies do not show a difference inrisk.The most commonly occurring THM is chloroform. In pure form this has stronganaesthetic properties and was one of the first substances used as an anaesthetic. Longterm exposure to dose levels of chloroform in excess of 15 mg/kg can induce pathologicalchanges in the liver, kidney and thyroid gland. When fed to experimental animals in highdosages over a long period, tumour induction has been observed. Epidemiological studieson human populations have been equivocal at exposure levels normally encountered.Extrapolation from animal studies suggests that the risk level for man at a lifetime exposureto 200 &#181;g/R in drinking water is a cancer risk of one in 10 , over and above the background 5cancer risk.For bromoform, there is evidence of toxicity at high levels of exposure and equivocalevidence of tumour induction, as in the case of chloroform, with a risk level of one in 105to a concentration of 100 &#181;g/R for lifetime exposure. In the case of bromodichloromethane, toxicity with liver and kidney damage is observed inexperimental animals at high levels with long-term exposure. The cancer risk level for a onein 10 incidence over a lifetime, is extrapolated from animal experiments to give a5concentration of 60 &#181;g/R in drinking water.Dibromochloromethane has similar toxic and carcinogenic risks to bromoform with a risklevel of one in 10 for a lifetime risk of cancer, at a concentration of 100 &#181;g/R in drinking 5water</td>
<td>Most forms of THMs are volatile. Treatment methods make use of this and subject the  water to air stripping in a vertical tower using a countercurrent stream of air blown upthrough the tower to strip the volatile substances into the atmosphere.However, some THMs are not easily volatilised and treatment of the raw water to removethe THM precursors (such as humic substances), may be required. Methods for removalinclude:! Slow sand filtration to remove trace organics from the water.! Coagulation, flocculation, clarification and filtration to remove particulate matterincluding organic colloids.! Adsorption of the organics onto activated carbon.! Oxidation of the organics using a powerful oxidising agent such as hydrogen, peroxide,ozone or peroxone. Chlorine is not a suitable oxidant as it will form THMs.A number of these methods may need to be applied in succession to achieve the requiredwater quality. High levels of treatment skills are needed to achieve satisfactory results,together with sophisticated analytical facilities.</td>
</tr>
<tr>
<td>Chromium  </td>
<td>health</td>
<td>The International Agency for Research on Cancer (IARC) of the WHO has classified chromium (VI) as a known human carcinogen (Group 1) and chromium (III) as not classified as to its carcinogenicity to humans (Group 3). Chromium (VI) compounds are active in a wide range of in vitro and in vivo genotoxicity tests. There are no adequate toxicity studies available to provide a basis for a No Observed Adverse Effect Level, or NOAEL. The guideline value was first proposed in 1958 for hexavalent chromium, based on health concerns, but was later changed to a guideline for total chromium because of difficulties in analysing for the hexavalent form only. Provisional guideline value for total chromium: 0.05 mg/l (50 ?g/l)</td>
<td>Chromium(VI) is the most soluble of the chromium species and removal thereof requires pretreatment of chromium(VI) to a more easily perceptible species. Therefore, removal of chromium(VI) from water requires the reduction of chromium(VI) to the trivalent form with ferrous sulphate, or by reaction with oxidisable organic matter. The trivalent chromium can then be removed by various processes, including: Precipitation and flocculation as chromium(III) hydroxide with lime and alum or ferric salts, followed by settlement and filtration. The process needs careful monitoring to ensure effective removal of chromium; and ! Removal with reverse osmosis or ion exchange. Alternative methods are available for adsorbing chromium(VI) onto ferric hydroxide precipitates. However, these are not as efficient as methods which rely on the reduction of chromium(VI), followed by precipitation of chromium(III) or chromium(II) hydroxides when the pH is raised. All processes produce a watery sludge or concentrate stream that may be rich in chromium, and present disposal difficulties</td>
</tr>
<tr>
<td>Cobalt  </td>
<td>health</td>
<td> </td>
<td> </td>
</tr>
<tr>
<td>Colour Pt-Co</td>
<td>aesthetic</td>
<td>No direct health effects result from the presence of colour in drinking water except whencolourants are toxic. Aesthetic effects are mainly visual but some colourants may stain orotherwise affect household appliances, for example, iron or manganese.</td>
<td>Colour in water supplies is caused by a variety of agents. Different methods may therefore be required to remove colour. These include: Filtration of the water through a slow sand filter. The biologically active surface layer on the filter removes colour by metabolising the organic material in the water. ! Some forms of colour in water are amenable to removal by coagulation, flocculation, clarification (by settlement or flotation) and filtration. A further activated carbon filtration step may be beneficial. ! Some forms of colour in water are readily removed by strong oxidising agents such as ozone.  In many cases a combination of treatment processes will be required to achieve the water quality required. Some improvement in the colour of household water can be achieved by filtering it through a disposable activated carbon cartridge.</td>
</tr>
<tr>
<td>Conductivity at 25degC mS/m</td>
<td>aesthetic</td>
<td> Water has a marked, salty taste and would probably not be used on aesthetic grounds if alternative supplies are available.Some effects on plumbing and appliances, such as increased corrosion or scaling, may be expected</td>
<td>Although some salts, such as those of calcium, magnesium and certain heavy metals can be removed by chemical precipitation, most of the inorganic salts dissolved in water canonly be removed by distillation or by highly sophisticated physical-chemical separationtechnologies. All these technologies are characterised by their high cost and/or their highenergy requirements.The technologies available for reducing the concentration of TDS in water are:! Demineralisation in a mixed-bed ion exchange column, usually where the feed TDSconcentration is approximately 2 000 mg/R. Disposable ion exchange canisters can beused to produce potable water for domestic consumption whereas large banks of ionexchange filter beds, which are capable of being regenerated, are used on an industrialscale. Ion exchange processes are also used for the production of ultrapure water.! Treatment by membrane processes such as reverse osmosis or electrodialysis wherethe TDS concentration is in the range of 2 000 - 3 500 mg/R. Small low-pressurereverse osmosis modules fed from a domestic supply line reliably produce potable waterfor household consumption and are easily replaced after one to three years if themembrane becomes fouled through scaling. Large-scale treatment is achieved withbanks of reverse osmosis modules in parallel.! Distillation, in cases where the TDS concentration is approximately 10 000 mg/R.All the process alternatives are usually fouled by suspended matter and may also beimpeded by severe scaling from hard waters. All large-scale processes require high levelsof design, operator and maintenance skills. Furthermore, all processes produce aconcentrated waste stream of the salts removed from the water and may cause disposaldifficulties.</td>
</tr>
<tr>
<td>Copper </td>
<td>health</td>
<td>At relatively low concentrations copper imparts a strongly astringent taste to water and canalso give rise to staining of laundry and plumbing fittings. At higher concentrations theseeffects become progressively more severe. Ingestion of high concentrations of copperresults in gastrointestinal disturbances and possible liver, kidney and red blood cell damage.However, owing to the extremely disagreeable taste of water with high copperconcentrations, it is unlikely that such water would be consumed.</td>
<td>Copper in solution is most conveniently removed from water by either: ! Flocculation with alum or ferric salts at pH 6 - 7; this reduces the soluble copper concentration to a low level; or ! Raising the pH and precipitating the insoluble copper carbonate and hydroxide complexes with lime treatment. The precipitation is followed by settlement and filtration as in conventional water treatment. The precipitation process requires careful monitoring to ensure complete removal. A watery copper-rich sludge is generated in the process; this may present disposal difficulties.</td>
</tr>
<tr>
<td>Cyanide  </td>
<td>health</td>
<td> </td>
<td> </td>
</tr>
<tr>
<td>Cytosporidium species</td>
<td>health</td>
<td>Cysts (Giardia) and oocysts (Cryptosporidium) are part of the lifecycle of these protozoanparasites and are infective to humans. Infection occurs by ingestion of the cysts or oocystsand disease takes the form of gastroenteritis, diarrhoea, vomiting and anorexia. Acute,chronic and asymptomatic manifestations of infection are known. The infective dose forparasites is extremely low. Theoretically, one cyst or oocyst is sufficient to cause infection,and an infective dose of 10 Giardia cysts has been demonstrated.Most outbreaks of giardiasis and cryptosporidiosis are associated with untreated watersupplies, water that has been disinfected (for example, chlorinated) but has not been passedthrough slow sand filters, and a breakdown in conventional treatment.</td>
<td>Several conventional water purification processes, including sedimentation, absorption, coagulation and flocculation will all result in the partial removal of micro-organisms inwater. These processes, however, do not necessarily inactivate the micro-organisms andadditional disinfection processes need to be applied. Chlorine disinfection is often practised.Disinfection, however, requires careful process control of the disinfection species, dosageand contact time.In situations where no conventional treatment is practised, micro-organisms can bedestroyed by boiling the water before use.</td>
</tr>
<tr>
<td>Dibromochloromethane </td>
<td>health</td>
<td>The similarity in effects and risks of the four main THM compounds allow them to beevaluated as a group and in practice only the total THM value is of significance and not theindividual THM concentrations. The criteria indicate an average risk of contracting cancerof one in 10 , over and above the background risk at a total THM concentration of 1005&#181;g/R. This is greater than the &quot;application safety factor&quot; used in estimating human risk,which is in the order of 10 . Further, the apparently greater risk with3bromodichloromethane than with chloroform is vastly overshadowed by the uncertainty ofanimal to human extrapolations used in these calculations. Sufficient animal experimentsas well as confirmative epidemiological studies have shown that there is a very small butsignificant risk of increased cancer incidence of the bowel and bladder from drinkingchlorinated water as opposed to unchlorinated ground water. The risk levels are, however,at the borderline of detection and some well-designed studies do not show a difference inrisk.The most commonly occurring THM is chloroform. In pure form this has stronganaesthetic properties and was one of the first substances used as an anaesthetic. Longterm exposure to dose levels of chloroform in excess of 15 mg/kg can induce pathologicalchanges in the liver, kidney and thyroid gland. When fed to experimental animals in highdosages over a long period, tumour induction has been observed. Epidemiological studieson human populations have been equivocal at exposure levels normally encountered.Extrapolation from animal studies suggests that the risk level for man at a lifetime exposureto 200 &#181;g/R in drinking water is a cancer risk of one in 10 , over and above the background 5cancer risk.For bromoform, there is evidence of toxicity at high levels of exposure and equivocalevidence of tumour induction, as in the case of chloroform, with a risk level of one in 105to a concentration of 100 &#181;g/R for lifetime exposure. In the case of bromodichloromethane, toxicity with liver and kidney damage is observed inexperimental animals at high levels with long-term exposure. The cancer risk level for a onein 10 incidence over a lifetime, is extrapolated from animal experiments to give a5concentration of 60 &#181;g/R in drinking water.Dibromochloromethane has similar toxic and carcinogenic risks to bromoform with a risklevel of one in 10 for a lifetime risk of cancer, at a concentration of 100 &#181;g/R in drinking 5water</td>
<td>Most forms of THMs are volatile. Treatment methods make use of this and subject the  water to air stripping in a vertical tower using a countercurrent stream of air blown upthrough the tower to strip the volatile substances into the atmosphere.However, some THMs are not easily volatilised and treatment of the raw water to removethe THM precursors (such as humic substances), may be required. Methods for removalinclude:! Slow sand filtration to remove trace organics from the water.! Coagulation, flocculation, clarification and filtration to remove particulate matterincluding organic colloids.! Adsorption of the organics onto activated carbon.! Oxidation of the organics using a powerful oxidising agent such as hydrogen, peroxide,ozone or peroxone. Chlorine is not a suitable oxidant as it will form THMs.A number of these methods may need to be applied in succession to achieve the requiredwater quality. High levels of treatment skills are needed to achieve satisfactory results,together with sophisticated analytical facilities.</td>
</tr>
<tr>
<td>E.coli or Fecal coliforms</td>
<td>health</td>
<td>Faecal coliforms are primarily used to indicate the presence of bacterial pathogens such as Salmonella spp., Shigella spp. Vibrio cholerae, Campylobacter jejuni, Campylobacter coli, Yersinia enterocolitica and pathogenic E. coli. These organisms can be transmitted via the faecal/oral route by contaminated or poorly-treated drinking water and may cause diseases such as gastroenteritis, salmonellosis, dysentery, cholera and typhoid fever. The risk of being infected by microbial pathogens correlates with the level of contamination of the water and the amount of contaminated water consumed. Higher concentrations of faecal coliforms in water will indicate a higher risk of contracting waterborne disease, even if small amounts of water are consumed.</td>
<td>Several conventional water purification processes, including sedimentation, absorption, coagulation and flocculation will all result in the partial removal of micro-organisms inwater. These processes, however, do not necessarily inactivate the micro-organisms andadditional disinfection processes need to be applied. Chlorine disinfection is often practised.Disinfection, however, requires careful process control of the disinfection species, dosageand contact time.In situations where no conventional treatment is practised, micro-organisms can bedestroyed by boiling the water before use.</td>
</tr>
<tr>
<td>Fluoride as F-</td>
<td>health</td>
<td>If fluoride is ingested, it is almost completely absorbed, where after it is distributed throughout the body. Most of the fluoride is retained in the skeleton and a small proportion in the teeth. Fluoride accumulates most rapidly in the bones of the young, but continues to accumulate up to the age of 55. It is excreted primarily in urine. The rate of fluoride retention decreases with age, and most adults are considered to maintain a steady state whereby accumulation of toxic amounts of fluoride is avoided by a balance between skeletal sequestration and renal excretion. The difference between concentrations of fluoride that protect tooth enamel and those that cause discolouration is marginal. Discolouration of dental enamel and mottling occurs at concentrations in the range of 1.5 - 2.0 mg/R in persons whose teeth are undergoing mineralisation. Generally, children up to seven years of age are susceptible. High doses of fluoride interfere with carbohydrate, lipid, protein, vitamin, enzyme and mineral metabolism. Skeletal fluorosis may occur when concentrations of fluoride in water exceed 3 - 6 mg/R and becomes crippling at intakes of 20 - 40 mg/day. This is equivalent to a fluoride concentration of 10 - 20 mg/R, for a mean daily water intake of two litres. Systemic toxicity and interference with bone formation and metabolism occur at high concentrations. Chronic effects on the kidneys have been observed in persons with renal disorders and rarer problems, including effects on the thyroid gland, which may occur with long-term exposure to high fluoride concentrations. Acute toxic effects at high fluoride doses include haemorrhagic gastroenteritis, acute toxic nephritis and injury to the liver and heart- muscle tissues. Many symptoms of acute fluoride toxicity are associated with the ability of fluoride to bind to calcium. Initial symptoms of fluoride toxicity include vomiting, abdominal pain, nausea, diarrhoea and convulsions.</td>
<td>Fluoride is a relatively stable anion which is difficult to remove from water to the required concentration range. Although calcium fluoride is relatively insoluble, its solubility is anorder of magnitude higher than the levels which need to be achieved by treatment. Themethods for the removal of fluoride include:! Adsorption in a bed of activated alumina;! Removal in ion exchange columns along with other anions; and! Removal in membrane processes such as reverse osmosis and electrodialysis togetherwith virtually all other ions.Regeneration of the activated alumina or ion exchange bed produces a high fluoride streamwhich may pose disposal difficulties. A concentrated reject stream is also produced fromreverse osmosis and electrodialysis, hence possible disposal problems.The techniques used are sophisticated and relatively expensive both in capital and operatingcosts. High levels of skill are needed in the design, operation and maintenance of theequipment. </td>
</tr>
<tr>
<td>Free chlorine </td>
<td>health</td>
<td> </td>
<td> </td>
</tr>
<tr>
<td>Giardia species</td>
<td>health</td>
<td>Cysts (Giardia) and oocysts (Cryptosporidium) are part of the lifecycle of these protozoanparasites and are infective to humans. Infection occurs by ingestion of the cysts or oocystsand disease takes the form of gastroenteritis, diarrhoea, vomiting and anorexia. Acute,chronic and asymptomatic manifestations of infection are known. The infective dose forparasites is extremely low. Theoretically, one cyst or oocyst is sufficient to cause infection,and an infective dose of 10 Giardia cysts has been demonstrated.Most outbreaks of giardiasis and cryptosporidiosis are associated with untreated watersupplies, water that has been disinfected (for example, chlorinated) but has not been passedthrough slow sand filters, and a breakdown in conventional treatment.</td>
<td>Several conventional water purification processes, including sedimentation, absorption, coagulation and flocculation will all result in the partial removal of micro-organisms inwater. These processes, however, do not necessarily inactivate the micro-organisms andadditional disinfection processes need to be applied. Chlorine disinfection is often practised.Disinfection, however, requires careful process control of the disinfection species, dosageand contact time.In situations where no conventional treatment is practised, micro-organisms can bedestroyed by boiling the water before use.</td>
</tr>
<tr>
<td>Heterotrophic plate count</td>
<td>operational</td>
<td>Heterotrophic plate counts are used to assess the general bacterial content of water but do not necessarily represent the total bacterial population present. High heterotrophic plate counts in treated water indicate inadequate treatment of the water, post-treatment contamination or bacterial after growth in the distribution system. Therefore, pathogenic micro-organisms, bacteria, viruses or parasites could possibly be present in the water and pose a health risk when the water is used for domestic consumption.</td>
<td>Several conventional water purification processes, including sedimentation, absorption, coagulation and flocculation will all result in the partial removal of micro-organisms inwater. These processes, however, do not necessarily inactivate the micro-organisms andadditional disinfection processes need to be applied. Chlorine disinfection is often practised.Disinfection, however, requires careful process control of the disinfection species, dosageand contact time.In situations where no conventional treatment is practised, micro-organisms can bedestroyed by boiling the water before use.</td>
</tr>
<tr>
<td>Iron </td>
<td>health</td>
<td>Excessive ingestion of iron may result in haemochromatosis, wherein tissue damage occursas a consequence of iron accumulation. Haemochromatosis generally results fromprolonged consumption of acid foodstuffs cooked in kitchenware made of iron. Poisoningis rare since excessively high concentrations of iron do not occur naturally in water. Theextreme unpalatability of such water would probably prevent consumption. Further, ironin the distribution system promotes proliferation of iron-oxidising bacteria which oxidiseferrous iron to ferric iron, and manifest as slimy coatings in plumbing when the ironconcentration of the water in the distribution system approaches 0.3 mg/R. Effects arepredominantly aesthetic, such as the staining of enamelled surfaces of baths, hand basinsand lavatory cisterns/bowls and laundry. Iron causes discolouration of water supplies whenpresent at low concentrations in association with aluminium. Iron that settles out indistribution systems gradually reduces the flow rate of water. The only associated healtheffects are those that could arise from the presence of microbial deposits on internalsurfaces of plumbing. Iron complexed with humic acid, a natural water constituent in certain regions, causes abrown discolouration of water at high concentrations. This may be aestheticallyunacceptable, but has no adverse health implications</td>
<td>Iron in water supplies is most conveniently removed by applying conventional watertreatment processes of coagulation with lime or alum, followed by settlement and filtration.Iron can also be removed from water using an oxidising process which will convert the ironinto an insoluble hydroxide or hydrated oxide, removable by filtration. The followingtreatment approaches are used:! The water can be aerated by devices such as fountains, cascades or mechanicalaeration;! The addition of lime to the water will raise the pH and facilitate the oxidation of iron byair in the water, followed by settlement of the iron oxide;! The water can also be chemically oxidised by dosing with chlorine, hydrogen peroxide,ozone or other strong oxidants. On an industrial scale chlorine is commonly used as thechemical oxidant. Post-treatment, high levels of residual chlorine should be avoidedsince this may interfere with the quality of the water.Removal of iron can be achieved on a household scale by cascading the water through theair and allowing the iron oxide particles to settle. On an industrial scale the process usuallyneeds to be more closely controlled and monitored because the consequences of incompletetreatment may be severe.For the optimisation of treatment processes it is important to determine both the total anddissolved iron species and their relative concentrations.</td>
</tr>
<tr>
<td>Iron </td>
<td>aesthetic</td>
<td>Excessive ingestion of iron may result in haemochromatosis, wherein tissue damage occursas a consequence of iron accumulation. Haemochromatosis generally results fromprolonged consumption of acid foodstuffs cooked in kitchenware made of iron. Poisoningis rare since excessively high concentrations of iron do not occur naturally in water. Theextreme unpalatability of such water would probably prevent consumption. Further, ironin the distribution system promotes proliferation of iron-oxidising bacteria which oxidiseferrous iron to ferric iron, and manifest as slimy coatings in plumbing when the ironconcentration of the water in the distribution system approaches 0.3 mg/R. Effects arepredominantly aesthetic, such as the staining of enamelled surfaces of baths, hand basinsand lavatory cisterns/bowls and laundry. Iron causes discolouration of water supplies whenpresent at low concentrations in association with aluminium. Iron that settles out indistribution systems gradually reduces the flow rate of water. The only associated healtheffects are those that could arise from the presence of microbial deposits on internalsurfaces of plumbing. Iron complexed with humic acid, a natural water constituent in certain regions, causes abrown discolouration of water at high concentrations. This may be aestheticallyunacceptable, but has no adverse health implications</td>
<td>Iron in water supplies is most conveniently removed by applying conventional watertreatment processes of coagulation with lime or alum, followed by settlement and filtration.Iron can also be removed from water using an oxidising process which will convert the ironinto an insoluble hydroxide or hydrated oxide, removable by filtration. The followingtreatment approaches are used:! The water can be aerated by devices such as fountains, cascades or mechanicalaeration;! The addition of lime to the water will raise the pH and facilitate the oxidation of iron byair in the water, followed by settlement of the iron oxide;! The water can also be chemically oxidised by dosing with chlorine, hydrogen peroxide,ozone or other strong oxidants. On an industrial scale chlorine is commonly used as thechemical oxidant. Post-treatment, high levels of residual chlorine should be avoidedsince this may interfere with the quality of the water.Removal of iron can be achieved on a household scale by cascading the water through theair and allowing the iron oxide particles to settle. On an industrial scale the process usuallyneeds to be more closely controlled and monitored because the consequences of incompletetreatment may be severe.For the optimisation of treatment processes it is important to determine both the total anddissolved iron species and their relative concentrations.</td>
</tr>
<tr>
<td>Lead </td>
<td>health</td>
<td>There is no safe level of lead. Infants, children under six years, and pregnant women are at the highest risk.  Exposure to lead is associated with a wide range of effects, including various neurodevelopmental effects, mortality (mainly due to cardiovascular diseases), impaired renal function, hypertension, impaired fertility and adverse pregnancy outcomes. Impaired neuro-development in children is generally associated with lower blood lead concentrations than the other effects, the weight of evidence is greater for neurodevelopmental effects than for other health effects. For adults, the adverse effect associated with lowest blood lead concentrations for which the weight of evidence is greatest and most consistent is a lead-associated increase in systolic blood pressure. JECFA concluded that the effects on neurodevelopment and systolic blood pressure provided the appropriate bases for dose?response analyses. Based on the dose?response analyses, JECFA estimated that the previously established PTWI of 25 ?g/kg body weight is associated with a decrease of at least 3 intelligence quotient (IQ) points in children and an increase in systolic blood pressure of approximately 3 mmHg (0.4 kPa) in adults.An Acceptable Daily Intake (ADI) of 0.005 mg/kg body weight is calculated on the basis of a NOAEL of 0.47 mg/kg body weight per day in a 2-year toxicity/carcinogenicity study in rats in which an increased incidence of periacinar hepatocellular hypertrophy (liver abnormalities), increased liver and spleen weights and increased mortality occurred at higher doses, using an uncertainty factor of 100 (for interspecies and intra-species variation). </td>
<td>Lead in water supplies is most conveniently removed by applying conventional water treatment processes of coagulation with alum, ferric salts or lime followed by settlement andfiltration. The coagulation/flocculation process requires careful monitoring to ensure that removal is complete. A watery sludge containing lead is generated in the process, and may present disposal difficulties.</td>
</tr>
<tr>
<td>Manganese  </td>
<td>health</td>
<td>Manganese is an essential element, necessary for the human body in certain amounts. The level at which manganese benefits one person can correspond to the level at which it is harmful to others. Several epidemiological studies have suggested that soluble manganese is associated with adverse effects on learning in children.</td>
<td>Manganese is commonly removed from water using an oxidising process which converts the manganese into an insoluble oxide removable by filtration. At pH $ 9, manganese isoxidised by the dissolved oxygen in the water. If this is not possible, then a strongoxidising agent is used. (The reaction is considerably more difficult to achieve than withiron). Agents commonly used include:! Chlorine! Hydrogen peroxide! Potassium permanganate! OzoneWhere the oxidant used leaves a residual, as is the case with chlorine, the residual shouldbe removed before the water is supplied for use. Removal of manganese is difficult to achieve on a household scale, but some removal will be obtained by addition of sodium hypochlorite (household bleach) to the water. On an industrial scale the process usually needs to be closely controlled and monitored because the consequences of incomplete treatment may be severe.</td>
</tr>
<tr>
<td>Manganese  </td>
<td>aesthetic</td>
<td>Manganese is an essential element, necessary for the human body in certain amounts. The level at which manganese benefits one person can correspond to the level at which it is harmful to others. Several epidemiological studies have suggested that soluble manganese is associated with adverse effects on learning in children.</td>
<td>Manganese is commonly removed from water using an oxidising process which converts the manganese into an insoluble oxide removable by filtration. At pH $ 9, manganese isoxidised by the dissolved oxygen in the water. If this is not possible, then a strongoxidising agent is used. (The reaction is considerably more difficult to achieve than withiron). Agents commonly used include:! Chlorine! Hydrogen peroxide! Potassium permanganate! OzoneWhere the oxidant used leaves a residual, as is the case with chlorine, the residual shouldbe removed before the water is supplied for use. Removal of manganese is difficult to achieve on a household scale, but some removal will be obtained by addition of sodium hypochlorite (household bleach) to the water. On an industrial scale the process usually needs to be closely controlled and monitored because the consequences of incomplete treatment may be severe.</td>
</tr>
<tr>
<td>Mercury </td>
<td>health</td>
<td>The toxic effects of inorganic mercury compounds are seen mainly in the kidney. Food is the main source of mercury in non-occupationally exposed populations; the mean dietary intake of mercury in various countries ranges from 2 to 20 ug/day per person. Acute oral poisoning results primarily in haemorrhagic gastritis and colitis; the ultimate damage is to the kidney. The overall weight of evidence is that mercury (II) chloride has the potential to increase the incidence of some benign tumours at sites where tissue damage is apparent and that it possesses weak genotoxic activity but does not cause point mutations. TDI 2 ?g/kg body weight for inorganic mercury based on a NOAEL of 0.23 mg/kg body weight per day for kidney effects in a 26-week study in rats and applying an uncertainty factor of 100 (for interspecies and intra-species variation) after adjusting for daily dosing.</td>
<td>Current technology capable of removing inorganic mercury within the TWQR includes:! precipitation:- coprecipitation with aluminium hydroxide by addition of alum; and- coprecipitation with ferric hydroxide by addition of iron salts;! adsorption, using powdered or granular activated carbon; and! ion exchange, using appropriate resinsMercury residuals within the TWQR will not be consistently achieved without skilledprocess control of precipitation reactions; or careful monitoring for breakthrough fromactivated carbon or ion exchange columns. Inorganic mercury can be removed to asignificant extent (70 % - 80 %) by coagulation and flocculation with iron salts, followed,if necessary, by powdered activated carbon or granular activated carbon treatment.Organically-bound mercury is not satisfactorily removed by precipitation but is effectivelyremoved by adsorption to activated carbon.Disposal of the hazardous mercury-rich precipitates, regeneration solutions or loadedactivated carbon require appropriately designed and licensed facilities.</td>
</tr>
<tr>
<td>Microcystin  </td>
<td>health</td>
<td>Treatment of water containing algae can result in the breakdown of algal cells giving rise totastes and odours, which render the water less acceptable for domestic use. The presenceof algal cells in the reticulation system may also contribute to bacterial regrowth in thedistribution system and can give the treated water a greenish colour.Ingestion of the hepatotoxins in sufficient quantities can lead to endotoxic shock and liverhaemorrhage. Severe gastroenteritis, vomiting and liver function impairment in populationssupplied from water bodies dominated by blue-green algae have been noted. There is alsolimited evidence of an increased incidence of liver cancer in populations exposed to lowconcentrations of hepatotoxins in untreated surface water over an extended period.Incidences of neurotoxic poisoning from red tides are common in many coastal cities, butno incidence of widespread human diseases associated with freshwater algal neurotoxinshave been noted. Neurotoxic poisoning in other mammals has been recorded, and istypified by muscular tremors, paralysis and convulsions. Death is by respiratory arrest.During chlorination, algae and their extracellular products can serve as precursors for theformation of THMs. Long-term ingestion of excessive levels of THMs is associated witha small risk of developing gastrointestinal cancer.</td>
<td>Waters prone to algal blooms are typically dominated by one or two species. The speciespresent may also provide an indication of the problems that are likely to be encountered.For example, diatom algae are known to block filter apparatus, while many of theEuglenophytes can penetrate standard sand filtration systems. Blooms of blue-green algaeincrease the risk of toxin penetration of the treatment process, and Anabeana spp. can resultin taste and odour problems even when present in very low numbers.Effective removal of algae in the treatment process depends on the species present. In general removal requires coagulation, flocculation and/or sedimentation. Some species, forexample Microcystis spp, are buoyant and therefore lend themselves to dissolved airfloatation. Coagulants like aluminium sulphate or ferric chloride are conventionally used,with the addition of small doses of polyelectrolytes to assist flocculation, followed by deepbed or multimedia filtration. The use of activated carbon, in particular granular activatedcarbon (GAC), is an effective means of removing the algal toxins and other algal byproducts from treated water. In the absence of activated carbon treatment (which is expensive), care should be taken to remove whole cells before treatment with an oxidant,since oxidants cause cell lysis, and the release of toxins and other intracellular products.However, it has recently been indicated that a chlorine residual of 0.5 mg/R after 30 minutescontact time is sufficient to destroy acute toxicity of the hepatotoxins. Chlorination may,however, produce other potentially toxic by-products.</td>
</tr>
<tr>
<td>Monochloramine </td>
<td>health</td>
<td>The presence of odour in water is irritating and unpleasant and it may impart undesirableodours to food and drink prepared with such water. Where cooking of food is involved,common, water-associated odours such as those of geosmin and methylisoborneol (MIB), are evaporated off.In exceptional cases the odour of water may be particularly noticeable and objectionable,such as when bathing and showering in hot water as the odourants evaporate at elevatedtemperatures.Odour may be an indicator of potential health effects, if it is associated with the presenceof toxic organic substances. </td>
<td>The techniques for removal of odours from domestic water supplies depend on the nature and cause of the odour. For this reason the best methods are often identified empiricallyfrom a range of techniques. The following approaches are commonly used:! Because odours are generally characteristic of volatile substances, some are effectivelyremoved by aeration of the water, or by blowing air counter-current to the water flowthrough a stripping tower.! With some waters, odours may be reduced or eliminated by the coagulation,flocculation, settlement and filtration process, but this is commonly a preliminary stepto be followed by either or both of the following processes.! Adsorption of odours using either powdered activated carbon dosed into the waterupstream of the filter, or by passing the water through a filter charged with granularactivated carbon which may need steam stripping or regeneration periodically. Smalldisposable cartridges of activated carbon are commonly used to remove tastes andodours from drinking water in domestic households. However, care should be takenwith timely replacement of the cartridges, since clogged cartridges promote bacterialand algal growth.! Oxidation of odours with powerful oxidants such as ozone or hydrogen peroxide areparticularly suitable because they leave no residuals after treatment. Chlorine is seldomsuitable because of its propensity to combine with many of the odour-causing organicsubstances to form strongly tasting components.Depending on the source of the odour it is often necessary to use two or more of theremoval techniques in series. The ?off-gas? from a stripping process may cause localisedair pollution unless passed through a chemical scrubber system or a biological filter.</td>
</tr>
<tr>
<td>Nickel </td>
<td>health</td>
<td> </td>
<td> </td>
</tr>
<tr>
<td>Nitrate as N </td>
<td>health</td>
<td>Upon absorption, nitrite combines with the oxygen-carrying red blood pigment,haemoglobin, to form methaemoglobin, which is incapable of carrying oxygen. Thiscondition is termed methaemoglobinaemia. The reaction of nitrite with haemoglobin canbe particularly hazardous in infants under three months of age and is compounded whenthe intake of Vitamin C is inadequate.Metabolically, nitrates may react with secondary and tertiary amines and amides, commonlyderived from food, to form nitrosamines which are known carcinogens.</td>
<td>Nitrate is not readily removed from domestic water supplies. Some reduction of nitrate may be achieved using slow sand filtration, but the method is not reliable. Biologicalreduction of nitrate to nitrogen gas (denitrification) is feasible in the presence of a suitablecarbon source, but the increase in carbonaceous matter is not compatible with a high qualitywater supply. Non-specific methods of removing nitrate include:! Passing the water stream through an ion exchange column with a selective affinity fornitrates. The method is expensive because other anions will be removed at the sametime, depending on the nature of the resin used. However, it may be attractive on ahousehold scale where only water used for drinking purposes is treated.! Reverse osmosis, which will remove nitrate effectively from water, along with highpercentages of virtually all other ions and many organic compounds. A low-pressurehome unit will conveniently treat small quantities of drinking water satisfactorily. Themodule is replaced when it begins to block through fouling or scaling.On a commercial scale the processes described require competent operation, control andmaintenance.</td>
</tr>
<tr>
<td>Nitrate-Nitrite ratio</td>
<td>health</td>
<td>Upon absorption, nitrite combines with the oxygen-carrying red blood pigment,haemoglobin, to form methaemoglobin, which is incapable of carrying oxygen. Thiscondition is termed methaemoglobinaemia. The reaction of nitrite with haemoglobin canbe particularly hazardous in infants under three months of age and is compounded whenthe intake of Vitamin C is inadequate.Metabolically, nitrates may react with secondary and tertiary amines and amides, commonlyderived from food, to form nitrosamines which are known carcinogens.</td>
<td>Nitrate is not readily removed from domestic water supplies. Some reduction of nitrate may be achieved using slow sand filtration, but the method is not reliable. Biologicalreduction of nitrate to nitrogen gas (denitrification) is feasible in the presence of a suitablecarbon source, but the increase in carbonaceous matter is not compatible with a high qualitywater supply. Non-specific methods of removing nitrate include:! Passing the water stream through an ion exchange column with a selective affinity fornitrates. The method is expensive because other anions will be removed at the sametime, depending on the nature of the resin used. However, it may be attractive on ahousehold scale where only water used for drinking purposes is treated.! Reverse osmosis, which will remove nitrate effectively from water, along with highpercentages of virtually all other ions and many organic compounds. A low-pressurehome unit will conveniently treat small quantities of drinking water satisfactorily. Themodule is replaced when it begins to block through fouling or scaling.On a commercial scale the processes described require competent operation, control andmaintenance.</td>
</tr>
<tr>
<td>Nitrite as N </td>
<td>health</td>
<td>Upon absorption, nitrite combines with the oxygen-carrying red blood pigment,haemoglobin, to form methaemoglobin, which is incapable of carrying oxygen. Thiscondition is termed methaemoglobinaemia. The reaction of nitrite with haemoglobin canbe particularly hazardous in infants under three months of age and is compounded whenthe intake of Vitamin C is inadequate.Metabolically, nitrates may react with secondary and tertiary amines and amides, commonlyderived from food, to form nitrosamines which are known carcinogens.</td>
<td>Nitrate is not readily removed from domestic water supplies. Some reduction of nitrate may be achieved using slow sand filtration, but the method is not reliable. Biologicalreduction of nitrate to nitrogen gas (denitrification) is feasible in the presence of a suitablecarbon source, but the increase in carbonaceous matter is not compatible with a high qualitywater supply. Non-specific methods of removing nitrate include:! Passing the water stream through an ion exchange column with a selective affinity fornitrates. The method is expensive because other anions will be removed at the sametime, depending on the nature of the resin used. However, it may be attractive on ahousehold scale where only water used for drinking purposes is treated.! Reverse osmosis, which will remove nitrate effectively from water, along with highpercentages of virtually all other ions and many organic compounds. A low-pressurehome unit will conveniently treat small quantities of drinking water satisfactorily. Themodule is replaced when it begins to block through fouling or scaling.On a commercial scale the processes described require competent operation, control andmaintenance.</td>
</tr>
<tr>
<td>pH at 25degC</td>
<td>operational</td>
<td>The selection of raw water as a drinking water source is never based solely on pH. Dangerto health would result primarily from the presence of metal ions, which are more likely toinfluence selection than the pH value. A direct relationship between the pH of drinkingwater and human health effects is difficult, if not impossible to establish since pH is veryclosely associated with other aspects of water quality.The taste of water, its corrosivity and the solubility and speciation of metal ions are allinfluenced by pH. At low pH water may taste sour, while at high pH water tastes bitter orsoapy. The potential toxicity of metal ions and chemicals which can be protonated, forexample ammonia, is influenced by pH. Changes in pH affect the degree of dissociationof weak acids and bases. This effect is of special importance because the toxicity of manycompounds is affected by their degree of dissociation.Corrosion in the water supply system is a major source of metal contamination in drinkingwater. Metals that have the potential for causing such contamination are lead, copper andzinc. Lead is subject to corrosion at a pH higher than 12. Corrosion of cadmium is onlysignificant below pH 6. Other metals which are frequently used in household plumbing andthat may be affected by pH are copper and zinc.</td>
<td>The main significance of pH in domestic water supplies relates to its effects on water treatment processes. The pH of water can be adjusted up or down by the addition of analkali or an acid.Commonly used alkaline reagents are sodium carbonate, sodium hydroxide and lime.Acidic reagents commonly used are carbon dioxide (a gas which forms carbonic acid inwater), hydrochloric acid or sulphuric acid. The reagent is usually added in dilute formusing a dosing pump controlled by a pH monitor.The adjustment of pH in water will inevitably increase the salinity of the water by addingions such as sodium, carbonate, hydroxyl, sulphate or chloride. Reagents should be chosento minimise secondary effects. For certain purposes the pH of the water will need to bestabilised to within a chosen range by the addition of buffering reagents.The handling of acids and alkalis is often hazardous requiring special precautions in theform of protective clothing and in materials used in the manufacture of the dosingequipment.</td>
</tr>
<tr>
<td>pH at 25degC</td>
<td>operational</td>
<td>The selection of raw water as a drinking water source is never based solely on pH. Dangerto health would result primarily from the presence of metal ions, which are more likely toinfluence selection than the pH value. A direct relationship between the pH of drinkingwater and human health effects is difficult, if not impossible to establish since pH is veryclosely associated with other aspects of water quality.The taste of water, its corrosivity and the solubility and speciation of metal ions are allinfluenced by pH. At low pH water may taste sour, while at high pH water tastes bitter orsoapy. The potential toxicity of metal ions and chemicals which can be protonated, forexample ammonia, is influenced by pH. Changes in pH affect the degree of dissociationof weak acids and bases. This effect is of special importance because the toxicity of manycompounds is affected by their degree of dissociation.Corrosion in the water supply system is a major source of metal contamination in drinkingwater. Metals that have the potential for causing such contamination are lead, copper andzinc. Lead is subject to corrosion at a pH higher than 12. Corrosion of cadmium is onlysignificant below pH 6. Other metals which are frequently used in household plumbing andthat may be affected by pH are copper and zinc.</td>
<td>The main significance of pH in domestic water supplies relates to its effects on water treatment processes. The pH of water can be adjusted up or down by the addition of analkali or an acid.Commonly used alkaline reagents are sodium carbonate, sodium hydroxide and lime.Acidic reagents commonly used are carbon dioxide (a gas which forms carbonic acid inwater), hydrochloric acid or sulphuric acid. The reagent is usually added in dilute formusing a dosing pump controlled by a pH monitor.The adjustment of pH in water will inevitably increase the salinity of the water by addingions such as sodium, carbonate, hydroxyl, sulphate or chloride. Reagents should be chosento minimise secondary effects. For certain purposes the pH of the water will need to bestabilised to within a chosen range by the addition of buffering reagents.The handling of acids and alkalis is often hazardous requiring special precautions in theform of protective clothing and in materials used in the manufacture of the dosingequipment.</td>
</tr>
<tr>
<td>Phenols </td>
<td>aesthetic</td>
<td>Phenol and chlorophenols impart unpleasant tastes and odours to water at concentrationsseveral orders of magnitude lower than the toxic limits. A toxic concentration of 3.0 mg/Ris given for phenol by the WHO, 1984. The ingestion of a concentrated solution of phenolwill result in severe pain and shock with renal damage, circulatory collapse and death. Thefatal dose is of the order of 1500 mg.</td>
<td>Phenolic compounds are not effectively removed from water using conventional water treatment techniques. The methods most commonly used include:! Oxidation: Phenols can be destroyed by the action of strong oxidising agents such asozone. Chlorine should not be used since it combines with phenols to form stronglytasting chlorophenols.! Adsorption: Trace concentrations of phenols can be removed by filtering the waterthrough a granular activated carbon column. The activated carbon column can bewashed with a sodium hydroxide solution to remove the adsorbed phenols as phenates.</td>
</tr>
<tr>
<td>Selenium  </td>
<td>health</td>
<td>The norm is based on the allocation of 20 % of the &quot;no-observed-adverse-effect&quot; level inwater. There is more data on the toxicity of selenium to animals than to humans. Thecriteria for humans has therefore been set at precautionary levels. Animals usually getselenium poisoning from their feed intake rather than from water, for example, ingestion ofselenium accumulator plants.Toxic effects of selenium become apparent at intakes 10 times or more of therecommended nutritional requirement. Effects include liver damage and impairment ofgrowth of nails and hair.</td>
<td>Selenium in water supplies is most effectively removed by one of two processes:! Coagulation and precipitation by treatment with lime or ferric chloride at pH valuesgreater than 8.5. Careful monitoring is needed to ensure effective removal.! Adsorption onto activated alumina at low pH levels.The processes involved require skilled operation and process control. Both processesproduce a waste stream that may be rich in selenium, presenting disposal difficulties.</td>
</tr>
<tr>
<td>Sodium </td>
<td>aesthetic</td>
<td>The taste threshold for sodium in water varies from 135 - 200 mg/R, depending on theassociated anion. The common ones include chloride, sulphate, nitrate, bicarbonate andcarbonate. Sodium intake can exacerbate certain disease conditions. Persons suffering fromhypertension, cardiovascular or renal diseases, should restrict their sodium intake. In thecase of bottle-fed infants, sodium intake should also be restricted. </td>
<td>Sodium can be removed from water together with other ions which constitute the total dissolved solids (TDS) by the following desalination processes :! Demineralisation in a mixed-bed ion exchange column, usually where the feed TDSis up to about 2 000 mg/R.! Treatment by membrane processes such as reverse osmosis or electrodialysis, wherethe TDS concentration is in the range of 2 000 - 35 000 mg/R.! Distillation, in cases where the TDS is 10 000 mg/R and more.Demineralisation by ion exchange can be used to produce low-sodium, potable water on ahousehold scale using disposable ion exchange cartridges, or on a commercial or industrialscale using banks of large, ion exchange filter beds which are capable of being regenerated.Small volumes of low-sodium potable water can be reliably produced on a household scaleusing small low-pressure reverse osmosis modules fed from the domestic water supply line.These are easily replaced after one to three years if the membrane becomes fouled throughscaling. Large-scale water treatment is achieved using banks of reverse osmosis modulesin parallel.All of the processes are easily fouled by suspended matter and are prone to scaling withhard waters. All of the processes produce a concentrated waste stream of the salts that maycause disposal difficulties. If used on a large scale, all of the processes require high levelsof design, operator and maintenance skills.</td>
</tr>
<tr>
<td>Sulfate as SO4-  </td>
<td>health</td>
<td>The major health effect observed being a laxative action. The U.S. EPA proposed a Maximum Contaminant Level Goal in the Safe Drinking Water Act of either 400 or 500 mg/L to protect infants and identified a LOAEL (Lowest-Observed-Adverse-Effect-Level) of 630 mg/L based on diarrhoea in infants receiving formula made with high-sulphate water (U.S. EPA, 1990). The Drinking Water Standards of the U.S. Public Health Service recommend that sulphate in water should not exceed 250 mg/L, except when no more suitable supplies are or can be made available. Sulphates can contribute to an undesirable taste in water with a taste threshold being 300-400 mg/L (NAS, 1977), and a guidance value of 400 mg/L based on aesthetic quality has been suggested (WHO, 1984b). </td>
<td>Sulphate can be removed from water by one of the following processes : Ion exchange in an anion exchange column, which will remove all anions. ! Any desalination technique in which scaling due to insoluble sulphate can be avoided or tolerated. These include: - demineralisation in mixed bed ion exchange columns; - membrane treatment by reverse osmosis or electrodialysis; - a range of distillation processes. ! Precipitation with calcium or barium salts followed by settlement and filtration to remove the insoluble calcium or barium sulphate. Barium is strongly toxic and should not be used for the removal of sulphate from water which will be used for domestic purposes, or which may come into contact with foodstuffs. Calcium salts will not reduce sulphate concentrations of 2 000 mg/R or less. Precipitation is only suitable for industrial application, although more commonly the method of choice is ion exchange or membrane treatment. On a household scale, small volumes of water for potable use can be produced by using disposable ion exchange cartridges, or low pressure reverse osmosis modules which are replaceable when the membrane becomes fouled through scaling. All of the processes produce a concentrated waste stream or slurry which may cause disposal difficulties. The industrial scale processes require high levels of design, operator and maintenance skills.</td>
</tr>
<tr>
<td>Sulfate as SO4-  </td>
<td>aesthetic</td>
<td>The major health effect observed being a laxative action. The U.S. EPA proposed a Maximum Contaminant Level Goal in the Safe Drinking Water Act of either 400 or 500 mg/L to protect infants and identified a LOAEL (Lowest-Observed-Adverse-Effect-Level) of 630 mg/L based on diarrhoea in infants receiving formula made with high-sulphate water (U.S. EPA, 1990). The Drinking Water Standards of the U.S. Public Health Service recommend that sulphate in water should not exceed 250 mg/L, except when no more suitable supplies are or can be made available. Sulphates can contribute to an undesirable taste in water with a taste threshold being 300-400 mg/L (NAS, 1977), and a guidance value of 400 mg/L based on aesthetic quality has been suggested (WHO, 1984b). </td>
<td>Sulphate can be removed from water by one of the following processes : Ion exchange in an anion exchange column, which will remove all anions. ! Any desalination technique in which scaling due to insoluble sulphate can be avoided or tolerated. These include: - demineralisation in mixed bed ion exchange columns; - membrane treatment by reverse osmosis or electrodialysis; - a range of distillation processes. ! Precipitation with calcium or barium salts followed by settlement and filtration to remove the insoluble calcium or barium sulphate. Barium is strongly toxic and should not be used for the removal of sulphate from water which will be used for domestic purposes, or which may come into contact with foodstuffs. Calcium salts will not reduce sulphate concentrations of 2 000 mg/R or less. Precipitation is only suitable for industrial application, although more commonly the method of choice is ion exchange or membrane treatment. On a household scale, small volumes of water for potable use can be produced by using disposable ion exchange cartridges, or low pressure reverse osmosis modules which are replaceable when the membrane becomes fouled through scaling. All of the processes produce a concentrated waste stream or slurry which may cause disposal difficulties. The industrial scale processes require high levels of design, operator and maintenance skills.</td>
</tr>
<tr>
<td>Total coliforms count/100ml</td>
<td>operational</td>
<td>Total coliform counts are primarily used in the evaluation of water treatment processes.They indicate microbial growth in the distribution system or post-treatment contaminationof drinking water. The total coliform group includes bacteria of faecal origin and indicates the possiblepresence of bacterial pathogens such as Salmonella spp., Shigella spp., Vibrio cholerae,Campylobacter jejuni, C. coli, Yersinia enterocolitica and pathogenic E. coli, especiallywhen detected in conjunction with other faecal coliforms. These organisms can causediseases such as gastroenteritis, salmonellosis, dysentery, cholera and typhoid fever. </td>
<td>Several conventional water purification processes, including sedimentation, absorption, coagulation and flocculation will all result in the partial removal of micro-organisms inwater. These processes, however, do not necessarily inactivate the micro-organisms andadditional disinfection processes need to be applied. Chlorine disinfection is often practised.Disinfection, however, requires careful process control of the disinfection species, dosageand contact time.In situations where no conventional treatment is practised, micro-organisms can bedestroyed by boiling the water before use.</td>
</tr>
<tr>
<td>Total dissolved solids </td>
<td>aesthetic</td>
<td>Low concentrations of particularly calcium and magnesium salts have nutritional value,although water with an extremely low TDS concentration may be objectionable because of its flat, insipid taste. Health effects related to TDS are minimal at concentrations below 2000 - 3 000 mg/R TDS. In contrast, high concentrations of salts impart an unpleasant tasteto water and may also adversely affect the kidneys.Some of the physiological effects which may be directly related to high concentrations ofdissolved salts include:! laxative effects, mainly from sodium sulphate and magnesium sulphate, see sulphate;! adverse effects of sodium on certain cardiac patients and hypertension sufferers;! effects of sodium on women with toxaemia associated with pregnancy; and! some effects on kidney function.Bathing and washing in water with excessively high concentrations of TDS may give riseto excessive skin dryness and hence discomfort. Soap may lather poorly or with difficulty,see calcium and magnesium.Chemical corrosion may occur when the alkalinity, i.e. the concentrations of carbonate,bicarbonate and hydroxide are low, the TDS concentration is high, particularly theconcentrations of chloride and sulphate, and the pH is low. Scaling may also occur, seecorrosion, calcium, magnesium and total hardness. Excessively high concentrations ofTDS may adversely affect plumbing and appliances and hence the maintenance andreplacement requirements.</td>
<td>Although some salts, such as those of calcium, magnesium and certain heavy metals can be removed by chemical precipitation, most of the inorganic salts dissolved in water canonly be removed by distillation or by highly sophisticated physical-chemical separationtechnologies. All these technologies are characterised by their high cost and/or their highenergy requirements.The technologies available for reducing the concentration of TDS in water are:! Demineralisation in a mixed-bed ion exchange column, usually where the feed TDSconcentration is approximately 2 000 mg/R. Disposable ion exchange canisters can beused to produce potable water for domestic consumption whereas large banks of ionexchange filter beds, which are capable of being regenerated, are used on an industrialscale. Ion exchange processes are also used for the production of ultrapure water.! Treatment by membrane processes such as reverse osmosis or electrodialysis wherethe TDS concentration is in the range of 2 000 - 3 500 mg/R. Small low-pressurereverse osmosis modules fed from a domestic supply line reliably produce potable waterfor household consumption and are easily replaced after one to three years if themembrane becomes fouled through scaling. Large-scale treatment is achieved withbanks of reverse osmosis modules in parallel.! Distillation, in cases where the TDS concentration is approximately 10 000 mg/R.All the process alternatives are usually fouled by suspended matter and may also beimpeded by severe scaling from hard waters. All large-scale processes require high levelsof design, operator and maintenance skills. Furthermore, all processes produce aconcentrated waste stream of the salts removed from the water and may cause disposaldifficulties.</td>
</tr>
<tr>
<td>Total organic carbon  </td>
<td>health</td>
<td>The DOC concentration in water per se has no direct health implications but, is an indicatorof the organic material content of the water. Such material may pass through the watertreatment process to the disinfection stage. If disinfection by chlorination is practised, theDOC concentration and content is a tentative indication of the potential for the formationof THMs by halogenation of dissolved organic precursors. Chloroform,dichlorobromomethane, dibromochloromethane and bromoform are some of the principalTHMs which may be formed.Chloroform has been implicated as a probable cause of drinking water-related cancer inlaboratory animals. However, a quantitative link between the DOC concentration and eithertrihalomethane formation or human health effects has not been established and studies ofdrinking waters throughout South Africa thus far, have found no causal relationshipbetween THM concentrations and cancer incidence and/or mortality. Further, it should alsobe noted that intake of THMs from other sources, for example food, far exceeds the intake from other environmental sources such as drinking water.</td>
<td>Removal of organic carbon from domestic water supplies can be achieved by a number of techniques. Assuming the residual concentrations are only marginally above acceptablelevels, the treatment methods include:! Filtration of the water through a slow sand filter. In time the filter develops a biofilmwhich metabolises the organic carbonaceous material in the water, effecting measurablepurification;! Some forms of organic carbon are amenable to removal by coagulation, flocculation,clarification (settlement or flotation) and filtration. An activated carbon filtration stepmay be beneficial; and! Organic carbon is readily oxidised by strong oxidising agents such as hydrogen peroxide,ozone or Peroxone.In many cases, a combination of treatment processes is necessary to achieve the waterquality required. Some improvement in the organic quality of household water can beachieved by filtering through disposable activated carbon cartridges. The strong oxidisingagents mentioned above are hazardous if handled carelessly.</td>
</tr>
<tr>
<td>Trihalomethane ratio</td>
<td>health</td>
<td>The similarity in effects and risks of the four main THM compounds allow them to beevaluated as a group and in practice only the total THM value is of significance and not theindividual THM concentrations. The criteria indicate an average risk of contracting cancerof one in 10 , over and above the background risk at a total THM concentration of 1005&#181;g/R. This is greater than the &quot;application safety factor&quot; used in estimating human risk,which is in the order of 10 . Further, the apparently greater risk with3bromodichloromethane than with chloroform is vastly overshadowed by the uncertainty ofanimal to human extrapolations used in these calculations. Sufficient animal experimentsas well as confirmative epidemiological studies have shown that there is a very small butsignificant risk of increased cancer incidence of the bowel and bladder from drinkingchlorinated water as opposed to unchlorinated ground water. The risk levels are, however,at the borderline of detection and some well-designed studies do not show a difference inrisk.The most commonly occurring THM is chloroform. In pure form this has stronganaesthetic properties and was one of the first substances used as an anaesthetic. Longterm exposure to dose levels of chloroform in excess of 15 mg/kg can induce pathologicalchanges in the liver, kidney and thyroid gland. When fed to experimental animals in highdosages over a long period, tumour induction has been observed. Epidemiological studieson human populations have been equivocal at exposure levels normally encountered.Extrapolation from animal studies suggests that the risk level for man at a lifetime exposureto 200 &#181;g/R in drinking water is a cancer risk of one in 10 , over and above the background 5cancer risk.For bromoform, there is evidence of toxicity at high levels of exposure and equivocalevidence of tumour induction, as in the case of chloroform, with a risk level of one in 105to a concentration of 100 &#181;g/R for lifetime exposure. In the case of bromodichloromethane, toxicity with liver and kidney damage is observed inexperimental animals at high levels with long-term exposure. The cancer risk level for a onein 10 incidence over a lifetime, is extrapolated from animal experiments to give a5concentration of 60 &#181;g/R in drinking water.Dibromochloromethane has similar toxic and carcinogenic risks to bromoform with a risklevel of one in 10 for a lifetime risk of cancer, at a concentration of 100 &#181;g/R in drinking 5water</td>
<td>Most forms of THMs are volatile. Treatment methods make use of this and subject the  water to air stripping in a vertical tower using a countercurrent stream of air blown upthrough the tower to strip the volatile substances into the atmosphere.However, some THMs are not easily volatilised and treatment of the raw water to removethe THM precursors (such as humic substances), may be required. Methods for removalinclude:! Slow sand filtration to remove trace organics from the water.! Coagulation, flocculation, clarification and filtration to remove particulate matterincluding organic colloids.! Adsorption of the organics onto activated carbon.! Oxidation of the organics using a powerful oxidising agent such as hydrogen, peroxide,ozone or peroxone. Chlorine is not a suitable oxidant as it will form THMs.A number of these methods may need to be applied in succession to achieve the requiredwater quality. High levels of treatment skills are needed to achieve satisfactory results,together with sophisticated analytical facilities.</td>
</tr>
<tr>
<td>Turbidity</td>
<td>operational</td>
<td>The consumption of turbid water per se does not have any direct health effects, butassociated effects due to microbial contamination or the ingestion of substances bound toparticulate matter, do. Turbidity can have a significant effect on the microbiological qualityof water. Microbial growth in water is most extensive on the surface of particulates andinside loose, naturally-occurring flocs. River silt also readily adsorbs viruses and bacteria.During treatment, micro-organisms become entrapped in the floc formed during coagulationand breakthrough of the floc may represent significant microbial contamination.Consumption of highly turbid, chlorinated water may therefore pose a health risk.Particulate matter can also protect bacteria and viruses against disinfection. The adsorptiveproperties of some suspended particles can lead to the entrapment of undesirable inorganicand organic compounds in water, including metal-humate complexes and herbicides (e.g.2,4-D, Paraquat, Diquat). This may interfere with the detection of such compounds, andcould be an indirect health risk.Turbidity may also be associated with the presence of inorganic ions such as manganese(II).For example, when water containing manganese(II) ions is treated with chlorine and leftto stand, slow reaction kinetics indicate that colloidal manganese(IV) oxide is formed,leading eventually to the formation of a fine precipitate.</td>
<td>The settleable fraction of the suspended matter in water will tend to gradually settle to theOptions bottom where the water is not disturbed. However, the smaller particles and colloidalfraction do not settle out and are kept in suspension by Brownian motion, as well as bymutual repulsion of the like-electrical charges which are often present on the surfaces of thesuspended matter. When a flocculant is added to a water, the electrical charges areneutralised and the particles cohere and settle out.Removal of turbidity from domestic or industrial water normally requires an effectivecoagulation and flocculation process following settlement or deep-bed or multimediafiltration, if the particles involved are colloidal in nature.Coagulants like aluminium sulphate or ferric chloride are conventionally used, with smalldoses of polyelectrolytes added to assist in flocculation. With many waters, small doses ofpolyelectrolytes alone may be sufficient to promote flocculation of the particles for removalby settlement and filtration.Silica sand filters are most commonly used in large-scale treatment plants. Multimediafilters of anthracite and garnet are also used, even though there is a growing tendency to usemembrane processes such as microfiltration or ultrafiltration in more critical applications.Filter backwash water may cause disposal difficulties. The processes require careful designand skilled monitoring and control. They are generally not suited to application on ahousehold scale.As the turbidity of water increases, the amount of chlorine required for disinfection of thewater increases. Low turbidity therefore minimises the required chlorine dose and reducesthe formation of chloro-organics that often give rise to taste and odour problems andtrihalomethanes. Due to the many advantages associated with water of low turbidity andthe relative ease of monitoring, it is often used as an indicator of potential water qualityproblems during treatment.</td>
</tr>
<tr>
<td>Turbidity</td>
<td>aesthetic</td>
<td>The consumption of turbid water per se does not have any direct health effects, butassociated effects due to microbial contamination or the ingestion of substances bound toparticulate matter, do. Turbidity can have a significant effect on the microbiological qualityof water. Microbial growth in water is most extensive on the surface of particulates andinside loose, naturally-occurring flocs. River silt also readily adsorbs viruses and bacteria.During treatment, micro-organisms become entrapped in the floc formed during coagulationand breakthrough of the floc may represent significant microbial contamination.Consumption of highly turbid, chlorinated water may therefore pose a health risk.Particulate matter can also protect bacteria and viruses against disinfection. The adsorptiveproperties of some suspended particles can lead to the entrapment of undesirable inorganicand organic compounds in water, including metal-humate complexes and herbicides (e.g.2,4-D, Paraquat, Diquat). This may interfere with the detection of such compounds, andcould be an indirect health risk.Turbidity may also be associated with the presence of inorganic ions such as manganese(II).For example, when water containing manganese(II) ions is treated with chlorine and leftto stand, slow reaction kinetics indicate that colloidal manganese(IV) oxide is formed,leading eventually to the formation of a fine precipitate.</td>
<td>The settleable fraction of the suspended matter in water will tend to gradually settle to theOptions bottom where the water is not disturbed. However, the smaller particles and colloidalfraction do not settle out and are kept in suspension by Brownian motion, as well as bymutual repulsion of the like-electrical charges which are often present on the surfaces of thesuspended matter. When a flocculant is added to a water, the electrical charges areneutralised and the particles cohere and settle out.Removal of turbidity from domestic or industrial water normally requires an effectivecoagulation and flocculation process following settlement or deep-bed or multimediafiltration, if the particles involved are colloidal in nature.Coagulants like aluminium sulphate or ferric chloride are conventionally used, with smalldoses of polyelectrolytes added to assist in flocculation. With many waters, small doses ofpolyelectrolytes alone may be sufficient to promote flocculation of the particles for removalby settlement and filtration.Silica sand filters are most commonly used in large-scale treatment plants. Multimediafilters of anthracite and garnet are also used, even though there is a growing tendency to usemembrane processes such as microfiltration or ultrafiltration in more critical applications.Filter backwash water may cause disposal difficulties. The processes require careful designand skilled monitoring and control. They are generally not suited to application on ahousehold scale.As the turbidity of water increases, the amount of chlorine required for disinfection of thewater increases. Low turbidity therefore minimises the required chlorine dose and reducesthe formation of chloro-organics that often give rise to taste and odour problems andtrihalomethanes. Due to the many advantages associated with water of low turbidity andthe relative ease of monitoring, it is often used as an indicator of potential water qualityproblems during treatment.</td>
</tr>
<tr>
<td>Uranium  </td>
<td>health</td>
<td>In general the effects of exposure to elevated levels of radioactivity in water are an increasein the cancer risk. The organ at risk for cancer will depend on the site in the body wherethe given radionuclide tends to accumulate. This in turn, depends on the chemical natureof the radionuclide. In the case of radon and its short-lived daughter nuclides, the primarytarget organ is the lungs and the risk is presented via inhalation of air contaminated withradon. This may occur on showering with radon-rich water in a poorly ventilated area.The radon in the air may arise from contaminated building materials from the underlyingground, or be transported via the water supply, particularly if this is ground water in an arearich in uraniferous deposits.In the case of radium and thorium, the target organ is the bony skeleton, because of theinsolubility of the phosphate salts. Uranium on the other hand tends to accumulate in thekidneys and the liver. In the case of uranium, chemical toxicity is of more concern thanthe radiological risk of cancer.Most of the effects of natural radioactivity described in the literature are for the elementsuranium, radium, radon and thorium. There is little known on the specific effects of lead210 and polonium-210, other than it is presumed that the major effect is as a consequenceof exposure to the mother nuclide radon-222.</td>
<td>Treatment options need to be tailored to the chemical nature of the major nuclide causing the radioactivity. In the case of radon, which is chemically inert, the radon may be removed by physical processes, such as aeration of the water. For the chemically-reactive radionuclides of uranium, thorium and radium, removal processes may range from optimisation of conventional flocculation processes through to processes such as concentrated lime treatment and ion-exchange or reverse osmosis where high removal efficiencies are required. The radioactivity concentration in the sludges or waste streams may present disposal problems. Treatment options for lead-210 are the same as for natural lead (see lead), while the treatment options for polonium are similar to those for Group VI elements in the periodic table (see selenium).</td>
</tr>
<tr>
<td>Vanadium  </td>
<td>health</td>
<td>Total dietary intake of vanadium is of relevance in assessing the effects of vanadium ratherthan the contribution of vanadium in water per se. Information on the toxic threshold ofvanadium in humans is rather sparse and animal studies suggest that there is a stronginteraction between dietary composition and susceptibility to symptoms of vanadiumpoisoning.Vanadium affects the metabolism of the amino acid cystine, resulting in a reduction of theconcentration of coenzyme A. Symptoms of vanadium toxicity include conjunctivitis,rhinitis, a sore throat and a persistent cough. Exposure to high concentrations of vanadiumcan cause severe chronic bronchitis.</td>
<td>Vanadium in water supplies is most conveniently removed by raising the pH and precipitating the insoluble vanadium salts after the addition of lime or iron salts in the pHrange of 8.5 - 11.5. Precipitation is followed by settlement and filtration as in conventionalwater treatment. The precipitation process requires careful monitoring to ensure thatremoval is complete.To achieve very low residuals, it may be necessary to pass the stream through an ionexchange column charged with the appropriate resin.A watery, vanadium-rich sludge or concentrate stream is generated in the processes thatmay present disposal difficulties.</td>
</tr>
<tr>
<td>Zinc </td>
<td>aesthetic</td>
<td>At concentrations sufficient to cause gastrointestinal disturbances, zinc imparts a bitterastringent taste, and an opalescent or milky appearance to water. It does not pose a hazardsince the vomiting reflex is activated to rid the body of high levels.</td>
<td>Zinc in water supplies is most conveniently removed by raising the pH and precipitating the insoluble zinc hydroxide with lime treatment in the pH range of 9.5 - 10.0. Precipitationis followed by settlement and filtration as in conventional water treatment. The precipitation process requires careful monitoring to ensure complete removal. A watery, zinc-rich sludge is generated in the process; this may present disposal difficulties.</td>
</tr>
</tbody></table>
        </div>

        
          <RouterLink class="button is-primary" to="wq-health-dashboard">
            <i class="material-icons">info</i>
            <span>Back to Water Quality Health Dashboard</span>
          </RouterLink>
        </div>
      </div>
    </section>
  </div>
</template>

<script lang="ts">
export default {
  name: 'Dashboard',
}
</script>

<style>
.hero-body {
  height: 100vh;
}
</style>